#! /usr/bin/python

############################################
# Author:    Russell.Ballestrini.net
# Date:      Fri Mar 18 15:56:59 EDT 2011
# License:   Public Domain
#
# Please leave this banner with the code
#
# todo: logging, verbose messages, 
#
############################################

import libvirt
import tarfile
import syslog
from re import findall
from time import sleep
from datetime import date
from sys import argv, exit
from optparse import OptionParser, OptionGroup

def connect():
    """ connect to qemu with read write access"""
    url = 'qemu:///system'
    c = libvirt.open( url )
    libvirt.registerErrorHandler( logit, 'libvirt error - ') # register logit as the error handler
    assert c, 'Failed to open connection ' + url
    return c

def backup( domList ):
    """ Accept a domList, run backup proceedure on each """
    
    tarList = [] # this will be filled with tar filenames

    shutdown( domList ) # shutdown all doms
    
    for dom in domList:
        if dom.isActive() == 0:
            xml = dom.XMLDesc( 0 )           
            disklist = findall( "<source file='(.*)'/>\n", xml )
            #filename = options.backpath + dom.name() + '-' + TODAY + '.tar.gz'
            filename = options.backpath + dom.name() + '.tar.gz'
            tar = tarfile.open( filename, 'w:gz' )
            logit( 'BACKUP', 'starting backup for ' + dom.name() + ' to ' + filename )
            tar.add( disklist[0] ) # we could loop and tar each disk file
            tar.close()
            logit( 'BACKUP', 'finished backing for ' + dom.name() )
            dom.create() # start dom
            sleep(5)
            if dom.isActive() == 1: # if dom is still active, there was a problem
                logit( 'START', dom.name() + ' has been started' )

        else: 
            logit( 'ERROR', 'we could not shutdown or destroy ' + dom.name() + 'and the BACKUP FAILED!'  )

def shutdown( domList, restart=False, wait=20 ):
    """Accept a list of dom objects, attempt to shutdown"""
    
    logit( 'SHUTDOWN', 'attempting to shutdown guests' )
    for dom in domList:
        if dom.isActive() == 1: # if active, shutdown    
            dom.shutdown()

    logit( 'WAIT', 'waiting ' + str(wait) + ' seconds for guests to shutdown' )
    sleep( wait ) 

    for dom in domList:
        if dom.isActive() == 1: # if active, destroy (pull plug)
            logit( 'DESTROY', 'attempting to destroy ' + dom.name()  )
            dom.destroy()
            sleep( wait/2 )
        if dom.isActive() == 0: 
            logit( 'SHUTDOWN', dom.name() + ' has been shutdown' )

    if restart: # if restart, turn all doms back on
        logit( 'START', 'attempting to start guests' )
        for dom in domList:
            if dom.isActive() == 1: # if dom is still active, there was a problem
                logit( 'ERROR', dom.name() + ' did not shutdown or destroy, and is still active' )
            else:    
                dom.create()
        
        sleep(wait/5)

        for dom in domList:
            if dom.isActive() == 1: # if dom is still active, there was a problem
                logit( 'START', dom.name() + ' has been started' )

    return True

def logit( context, message ):
    """log and error handler"""
    if type( message ) is tuple:
        message = message[2] # libvirt message is a tuple

    if options.verbose:
        print context + ': ' +  message

    syslog.openlog( 'virtback', 0, syslog.LOG_LOCAL3 )
    syslog.syslog( message )
    syslog.closelog()

def getoptions():
    """fetch cli args, parse and map to python, test sanity"""

    # create an option parcer object
    p = OptionParser()

    p.add_option( '-v', '--verbose', dest='verbose',
                  action='store_true', default=False,
                  help='verbose output to stdout [default: no output]' )

    p.add_option( '-p', '--backup-path', dest='backpath', metavar='\'PATH\'', default='/KVMBACK/',
                  help='backup path & trailing slash [default: \'/KVMBACK/\']' )

    # WARNING: Dangerous options below
    # create an option group g object for scary options

    g = OptionGroup( p, "Actions", "WARNING:  These options WILL reboot hosts!"  )
    
    g.add_option( '--backup-guests', dest='guests', metavar='\'domName1 domName2\'',
                  default=False, help='backup a list of guests (space delimited)' )

    g.add_option( '--backup-all-guests', dest='allbackup',
                  action='store_true', default=False,
                  help='backup and reboot ALL guests' )

    g.add_option( '--reboot-all-guests', dest='allreboot',
                  action='store_true', default=False,
                  help='reboot ALL guests' )

    g.add_option( '--reboot-host', dest='hostreboot',
                  action='store_true', default=False,
                  help='reboot HOST and ALL guests (requires root or sudo)' )

    # attach to the parser p object
    p.add_option_group( g )

    # parse options and args
    options, args = p.parse_args()

    # the actionsum should be 1 to continue
    actionsum = sum( [ bool(options.guests), options.allbackup, options.allreboot, options.hostreboot] )

    if actionsum== 1:
        return options
    else:
	exit("\nYou must have 1 action, no more, no less.\n\nRun 'virtback -h' for help.\n")

if __name__ == '__main__':
    """main choice logic"""

    TODAY = str( date.today() )
    
    # Get the list of dom objects based on cli options
    options = getoptions()

    c = connect() # connect to libvirt
    domList = [] # this will store the dom objects

    if options.guests: # list of guest names
        domNameList = options.guests.split()
        for domName in domNameList:
            #dom = c.lookupByName( domName )
            try:
                dom = c.lookupByName( domName )
                domList.append( dom )
            except libvirt.libvirtError:
                pass # logit was registered to libvirt error handler
        backup( domList )

    elif options.allbackup or options.allreboot or options.hostreboot:
        for id in c.listDomainsID(): # loop over the running ids
            domList.append( c.lookupByID( id ) )
        
        if options.allbackup:
            backup( domList )

        if options.allreboot:
            shutdown( domList, restart=True )

        if options.hostreboot:
            shutdown( domList )
            from os import system
            logit('restart', 'running init 6, restarting vm host' )
            system('init 6')

